

camera = 'FLASH.DIAG/CAMERA/OTR9FL2XTDS/';
cam_data = 'FLASH.DIAG/CAMERA/OTR9FL2XTDS/IMAGE_EXT_ZMQ'
charge='FLASH.DIAG/TOROID/7FL2XTDS/CHARGE.FLASH2';
TDSphase='FLASH.RF/LLRF.CONTROLLER/CTRL.POLARIX/SP.PHASE';
SPECTRUMXCOFM='FLASH.DIAG/CAMERA/OTR9FL2XTDS/SPECTRUM.X.CM',
SPECTRUMXMEAN='FLASH.DIAG/CAMERA/OTR9FL2XTDS/SPECTRUM.X.MEAN';
PHASE='FLASH.RF/LLRF.CONTROLLER/CTRL.POLARIX/SP.PHASE'
dipol='FLASH.MAGNETS/MAGNET.ML/D4FL2XTDS/CURRENT.SP';
